# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bitcoin_alpha.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 749)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 20, 751, 711))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.ButtonForUser = QtWidgets.QPushButton(self.tab1)
        self.ButtonForUser.setGeometry(QtCore.QRect(40, 260, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.ButtonForUser.setFont(font)
        self.ButtonForUser.setObjectName("ButtonForUser")
        self.lineEdit_create_user = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_create_user.setGeometry(QtCore.QRect(220, 260, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_create_user.setFont(font)
        self.lineEdit_create_user.setObjectName("lineEdit_create_user")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 150, 491, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.formLayoutWidget = QtWidgets.QWidget(self.tab2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 30, 491, 107))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.treeWidget = QtWidgets.QTreeWidget(self.tab2)
        self.treeWidget.setGeometry(QtCore.QRect(60, 250, 491, 211))
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.transport = QtWidgets.QPushButton(self.tab3)
        self.transport.setGeometry(QtCore.QRect(230, 300, 221, 34))
        self.transport.setObjectName("transport")
        self.label_6 = QtWidgets.QLabel(self.tab3)
        self.label_6.setGeometry(QtCore.QRect(70, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_transport = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_transport.setGeometry(QtCore.QRect(230, 150, 421, 31))
        self.lineEdit_transport.setObjectName("lineEdit_transport")
        self.trans_money = QtWidgets.QLineEdit(self.tab3)
        self.trans_money.setGeometry(QtCore.QRect(230, 210, 421, 31))
        self.trans_money.setObjectName("trans_money")
        self.label_7 = QtWidgets.QLabel(self.tab3)
        self.label_7.setGeometry(QtCore.QRect(70, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.lineEdit_create_user_real = QtWidgets.QLineEdit(self.tab4)
        self.lineEdit_create_user_real.setGeometry(QtCore.QRect(260, 260, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit_create_user_real.setFont(font)
        self.lineEdit_create_user_real.setObjectName("lineEdit_create_user_real")
        self.ButtonForUserReal = QtWidgets.QPushButton(self.tab4)
        self.ButtonForUserReal.setGeometry(QtCore.QRect(60, 260, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.ButtonForUserReal.setFont(font)
        self.ButtonForUserReal.setObjectName("ButtonForUserReal")
        self.tabWidget.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 170, 491, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(26)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.verticalLayout_4.addLayout(self.formLayout_7)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab5)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(70, 50, 491, 107))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_real = QtWidgets.QPushButton(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_real.setFont(font)
        self.pushButton_real.setObjectName("pushButton_real")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_real)
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.tab5)
        self.treeWidget_4.setGeometry(QtCore.QRect(70, 270, 491, 211))
        self.treeWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeWidget_4.setHeaderHidden(False)
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.tabWidget.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.transport_4 = QtWidgets.QPushButton(self.tab6)
        self.transport_4.setGeometry(QtCore.QRect(220, 310, 221, 34))
        self.transport_4.setObjectName("transport_4")
        self.label_27 = QtWidgets.QLabel(self.tab6)
        self.label_27.setGeometry(QtCore.QRect(40, 80, 161, 61))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_transport_4 = QtWidgets.QLineEdit(self.tab6)
        self.lineEdit_transport_4.setGeometry(QtCore.QRect(210, 100, 421, 31))
        self.lineEdit_transport_4.setObjectName("lineEdit_transport_4")
        self.trans_money_4 = QtWidgets.QLineEdit(self.tab6)
        self.trans_money_4.setGeometry(QtCore.QRect(210, 190, 421, 31))
        self.trans_money_4.setObjectName("trans_money_4")
        self.label_28 = QtWidgets.QLabel(self.tab6)
        self.label_28.setGeometry(QtCore.QRect(50, 180, 131, 61))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "比特币账户查询"))
        self.ButtonForUser.setText(_translate("MainWindow", "生成账户"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "生成Testnet账户"))
        self.label_5.setText(_translate("MainWindow", "查询结果"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">0</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "satoshi"))
        self.label_4.setText(_translate("MainWindow", "账户余额："))
        self.label.setText(_translate("MainWindow", "地址"))
        self.lineEdit.setText(_translate("MainWindow", "n1N4gibGTZyfovfoK6e85g9XoncAgrFATt"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "UTXO"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "查询Testnet账户"))
        self.transport.setText(_translate("MainWindow", "转账"))
        self.label_6.setText(_translate("MainWindow", "转账地址"))
        self.label_7.setText(_translate("MainWindow", "转账金额"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Testnet转账"))
        self.ButtonForUserReal.setText(_translate("MainWindow", "生成账户"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "生成比特币账户"))
        self.label_22.setText(_translate("MainWindow", "查询结果"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">0</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "satoshi"))
        self.label_25.setText(_translate("MainWindow", "账户余额："))
        self.label_26.setText(_translate("MainWindow", "地址"))
        self.lineEdit_4.setText(_translate("MainWindow", "18RKfuiBLFAq86dwyfUmX5gvFFZFYSMwgw"))
        self.pushButton_real.setText(_translate("MainWindow", "查询"))
        self.treeWidget_4.headerItem().setText(0, _translate("MainWindow", "UTXO"))
        self.treeWidget_4.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindow", "查询比特币账户"))
        self.transport_4.setText(_translate("MainWindow", "转账"))
        self.label_27.setText(_translate("MainWindow", "转账地址"))
        self.label_28.setText(_translate("MainWindow", "转账金额"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab6), _translate("MainWindow", "转账比特币账户"))
